# Generated by Django 3.2.5 on 2021-07-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='id',
        ),
        migrations.AlterField(
            model_name='slot',
            name='number',
            field=models.CharField(default='AX', max_length=255, primary_key=True, serialize=False),
        ),
    ]
